import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  sk: {
    "vehicleDetail.reportTitle": "Nahlásiť inzerát",
    "vehicleDetail.reportMessage": "Nahlasujem inzerát:",
    "vehicleDetail.reportSuccess": "Nahlásenie bolo odoslané adminom.",
    "vehicleDetail.reportError": "Nahlásenie sa nepodarilo odoslať.",
    "vehicleDetail.reportModalTitle": "Nahlásenie inzeratu",
    "vehicleDetail.reportPlaceholder": "Krátky popis problému...",
    "vehicleDetail.reportSend": "Odoslať",
    "vehicleDetail.reportSending": "Odosielam...",
    "vehicleDetail.reportCancel": "Zrušiť",
    "common.backHome": "Späť na domovskú stránku",
    "common.loading": "Načítavam...",
    "header.addListing": "Pridať inzerát",
    "header.sellers": "Zoznam predajcov",
    "header.favorites": "Obľúbené inzeráty",
    "header.messages": "Správy",
    "header.myAccount": "Môj účet",
    "header.admin": "Admin",
    "header.register": "Registrácia",
    "header.login": "Prihlásiť",
    "header.logout": "Odhlásiť",
    "home.loading": "Načítavam inzeráty...",
    "home.empty": "Žiadne inzeráty neboli nájdené",
    "favorites.title": "Obľúbené inzeráty",
    "favorites.loading": "Načítavam obľúbené inzeráty...",
    "favorites.empty": "Žiadne obľúbené inzeráty.",
    "favorites.error": "Nepodarilo sa načítať obľúbené inzeráty.",
    "messages.title": "Správy",
    "messages.subtitle": "Priamy chat medzi užívateľmi.",
    "messages.conversations": "Konverzácie",
    "messages.loadingThreads": "Načítavam...",
    "messages.noThreads": "Zatiaľ žiadne správy.",
    "messages.selectConversation": "Vyberte konverzáciu",
    "messages.loadingMessages": "Načítavam správy...",
    "messages.noMessages":
      "Zatiaľ žiadne správy. Kontaktujte používateľa cez inzerát.",
    "messages.messagePlaceholder": "Napísať správu...",
    "messages.messagePlaceholderEmpty": "Vyberte konverzáciu",
    "messages.send": "Odoslať",
    "messages.sending": "Odosielam...",
    "messages.errorUser": "Nepodarilo sa načítať používateľa.",
    "messages.errorThreads": "Nepodarilo sa načítať správy.",
    "messages.errorConversation": "Nepodarilo sa načítať konverzáciu.",
    "messages.errorSend": "Nepodarilo sa odoslať správu.",
    "messages.errorSelect": "Vyberte konverzáciu.",
    "messages.userFallback": "Používateľ",
    "messages.listingLabel": "Inzerát:",
    "addListing.titleAdd": "Pridať inzerát",
    "addListing.titleEdit": "Upraviť inzerát",
    "addListing.loginTitle": "Pridať inzerát",
    "addListing.loginText": "Na pridanie inzerátu sa prosím prihláste.",
    "addListing.loginButton": "Prihlásiť sa",
    "addListing.loading": "Načítavam...",
    "addListing.submitCreate": "Vytvoriť inzerát",
    "addListing.submitEdit": "Upraviť inzerát",
    "addListing.submitting": "Ukladám...",
    "addListing.labelTitle": "Názov",
    "addListing.labelLocation": "Lokalita",
    "addListing.labelBrand": "Značka",
    "addListing.labelBrandOther": "Názov značky",
    "addListing.labelModel": "Model",
    "addListing.labelModelOther": "Názov modelu",
    "addListing.brandPlaceholder": "Vyberte značku",
    "addListing.brandLoading": "Načítavam značky...",
    "addListing.modelPlaceholder": "Vyberte model",
    "addListing.modelLoading": "Načítavam modely...",
    "addListing.modelPlaceholderSelectBrand": "Najprv vyberte značku",
    "addListing.modelPlaceholderFillBrand": "Vyplňte názov modelu",
    "addListing.otherBrand": "Iná značka",
    "addListing.otherModel": "Iný model",
    "addListing.labelYear": "Rok",
    "addListing.labelMileage": "Nájazd",
    "addListing.labelEngine": "Objem motora (cc)",
    "addListing.labelPower": "Výkon (kW)",
    "addListing.labelFuel": "Palivo",
    "addListing.labelTransmission": "Prevodovka",
    "addListing.labelDrive": "Pohon",
    "addListing.labelPrice": "Cena",
    "addListing.labelCurrency": "Mena",
    "addListing.labelDescription": "Popis",
    "addListing.labelPhotos": "Fotky (poradie 1-10)",
    "addListing.photoChoose": "Vybrať fotku",
    "addListing.photoReplace": "Nahradiť",
    "addListing.fuelPetrol": "Benzín",
    "addListing.fuelDiesel": "Nafta",
    "addListing.fuelElectric": "Elektrina",
    "addListing.fuelHybrid": "Hybrid",
    "addListing.fuelLpg": "LPG",
    "addListing.transmissionManual": "Manuálna",
    "addListing.transmissionAutomatic": "Automatická",
    "addListing.driveEmpty": "Nezadané",
    "addListing.successCreate": "Inzerát bol vytvorený.",
    "addListing.successEdit": "Inzerát bol upravený.",
    "addListing.errorLoad": "Nepodarilo sa načítať inzerát.",
    "addListing.errorCreate": "Inzerát sa nepodarilo vytvoriť.",
    "addListing.errorBrands": "Nepodarilo sa načítať značky.",
    "footer.about": "O nás",
    "footer.contact": "Kontakt",
    "footer.support": "Podpora",
    "footer.reportListing": "Nahlásenie inzerátu",
    "footer.faq": "FAQ",
    "footer.register": "Registrovať",
    "footer.login": "Prihlásiť",
    "myAccount.title": "Môj účet",
    "myAccount.nameLabel": "Meno:",
    "myAccount.emailLabel": "Email:",
    "myAccount.phoneLabel": "Telefón:",
    "myAccount.createdAtLabel": "Dátum vytvorenia účtu:",
    "myAccount.accountTypeLabel": "Typ účtu:",
    "myAccount.accountTypeSeller": "Registrovaný predajca",
    "myAccount.accountTypeUser": "Bežný používateľ",
    "myAccount.sectionEditTitle": "Zmena údajov",
    "myAccount.formPhoneLabel": "Telefón",
    "myAccount.formNameLabel": "Meno",
    "myAccount.save": "Uložiť",
    "myAccount.saving": "Ukladám...",
    "myAccount.sellerModeTitle": "Režim predajcu",
    "myAccount.sellerModeDescription":
      "Aktivovaním sa zobrazíte v zozname predajcov.",
    "myAccount.sellerModeSaving": "Ukladám...",
    "myAccount.sellerModeDisable": "Vypnúť režim predajcu",
    "myAccount.sellerModeEnable": "Stať sa registrovaným predajcom",
    "myAccount.deleteTitle": "Vymazať účet",
    "myAccount.deleteDescription":
      "Po vymazaní účtu budú všetky údaje nenávratne odstránené.",
    "myAccount.deleteButton": "Vymazať môj účet",
    "myAccount.deleteButtonLoading": "Mažem účet...",
    "myAccount.errorLoad": "Nepodarilo sa načítať údaje používateľa.",
    "myAccount.errorEmptyName": "Meno nemôže byť prázdne.",
    "myAccount.successName": "Meno bolo úspešne zmenené.",
    "myAccount.errorUpdate": "Meno sa nepodarilo zmeniť.",
    "myAccount.successSeller": "Nastavenie predajcu bolo aktualizované.",
    "myAccount.errorSeller": "Nepodarilo sa upraviť mód predajcu.",
    "myAccount.confirmDelete":
      "Naozaj chcete vymazať svoj účet? Táto akcia je nevratná.",
    "myAccount.alertDeleted": "Váš účet bol úspešne vymazaný.",
    "myAccount.alertDeleteError": "Nastala chyba pri vymazávaní účtu.",
    "myAccount.loading": "Načítavam údaje...",
    "myAccount.userMissing": "Údaje používateľa nie sú dostupné.",
    "filterBar.brand": "Značka",
    "filterBar.model": "Model",
    "filterBar.all": "Všetky",
    "filterBar.priceFrom": "Cena od",
    "filterBar.priceTo": "Cena do",
    "filterBar.mileageFrom": "Nájazd od",
    "filterBar.mileageTo": "Nájazd do",
    "filterBar.yearFrom": "Rok výroby od",
    "filterBar.yearTo": "Rok výroby do",
    "filterBar.fuel": "Palivo",
    "filterBar.fuelPetrol": "Benzín",
    "filterBar.fuelDiesel": "Nafta",
    "filterBar.fuelElectric": "Elektrina",
    "filterBar.fuelHybrid": "Hybrid",
    "filterBar.reset": "Zrušiť filtre",
    "filterBar.sort": "Zoradenie",
    "filterBar.sortPriceAsc": "Najlacnejšie",
    "filterBar.sortPriceDesc": "Najdrahšie",
    "filterBar.sortNewest": "Najnovšie",
    "filterBar.sortOldest": "Najstaršie",
    "filterBar.pageSize": "Počet inzerátov",
    "listingCard.km": "km",
    "listingCard.currency": "EUR",
    "pagination.previous": "Predošlá",
    "pagination.next": "Ďalšia",
    "login.title": "Prihlásenie",
    "login.errorInvalid": "Nesprávny email alebo heslo.",
    "login.errorGeneric": "Prihlásenie zlyhalo.",
    "login.placeholderEmail": "Email",
    "login.placeholderPassword": "Heslo",
    "login.buttonLoading": "Prihlasujem...",
    "login.button": "Prihlásiť",
    "register.title": "Registrácia",
    "register.errorPasswordMatch": "Heslá sa nezhodujú.",
    "register.errorGeneric": "Registrácia zlyhala.",
    "register.placeholderName": "Meno",
    "register.placeholderEmail": "Email",
    "register.placeholderPassword": "Heslo",
    "register.placeholderPasswordConfirm": "Potvrdenie hesla",
    "register.buttonLoading": "Registrujem...",
    "register.button": "Registrovať",
    "sellers.title": "Zoznam predajcov",
    "sellers.loading": "Načítavam zoznam predajcov...",
    "sellers.errorLoad": "Nepodarilo sa načítať zoznam predajcov.",
    "sellers.empty": "Zatiaľ tu nie sú žiadni registrovaní predajcovia.",
    "sellers.listingsLink": "Inzeráty predajcu",
    "sellers.registeredLabel": "Registrovaný:",
    "sellerListings.loading": "Načítavam inzeráty...",
    "sellerListings.errorLoad": "Nepodarilo sa načítať inzeráty predajcu.",
    "sellerListings.backToSellers": "Naspäť na zoznam predajcov",
    "sellerListings.title": "Inzeráty predajcu",
    "sellerListings.unknownSeller": "predajca",
    "sellerListings.empty":
      "Pre tohto predajcu neboli nájdené žiadne inzeráty.",
    "vehicleDetail.notFound": "Inzerát neexistuje",
    "vehicleDetail.confirmDelete": "Naozaj chcete odstrániť inzerát?",
    "vehicleDetail.favoriteRemoveAlt": "Odobrať z obľúbených",
    "vehicleDetail.favoriteAddAlt": "Pridať medzi obľúbené",
    "vehicleDetail.previous": "Predchádzajúci",
    "vehicleDetail.next": "Ďalší",
    "vehicleDetail.brandLabel": "Značka:",
    "vehicleDetail.modelLabel": "Model:",
    "vehicleDetail.yearLabel": "Rok:",
    "vehicleDetail.mileageLabel": "Nájazd:",
    "vehicleDetail.fuelLabel": "Palivo:",
    "vehicleDetail.transmissionLabel": "Prevodovka:",
    "vehicleDetail.driveLabel": "Pohon:",
    "vehicleDetail.locationLabel": "Lokalita:",
    "vehicleDetail.contactTitle": "Kontakt",
    "vehicleDetail.contactButton": "Kontaktovať predajcu",
    "vehicleDetail.contactUnavailable": "Kontakt na predajcu nie je dostupný.",
    "vehicleDetail.descriptionTitle": "Popis",
    "vehicleDetail.adminBadge": "Admin režim",
    "vehicleDetail.editButton": "Upraviť inzerát",
    "vehicleDetail.deleteButton": "Odstrániť inzerát",
    "vehicleDetail.contactModalTitle": "Kontakt na predajcu",
    "vehicleDetail.emailLabel": "Email:",
    "vehicleDetail.phoneLabel": "Telefón:",
    "vehicleDetail.sendMessage": "Poslať správu",
    "about.title": "O nás",
    "about.p1":
      "VAII Inzercia je miesto, kde sa stretávajú kupujúci a predajcovia vozidiel. Naším cieľom je jednoduché, rýchle a bezpečné publikovanie inzerátov.",
    "about.p2":
      "Budujeme komunitu, ktorá si zakladá na dôveryhodnosti a prehľadnom vyhľadávaní. Vďaka filtrom, správam a obľúbeným inzerátom máte všetko dôležité na jednom mieste.",
    "about.p3":
      "Ak máte otázky alebo návrhy na zlepšenie, napíšte nám. Vaša spätná väzba je pre nás dôležitá.",
    "contact.title": "Kontakt",
    "contact.p1":
      "Máte otázku k inzerátu alebo potrebujete pomoc? Ozvite sa nám.",
    "contact.email": "Email",
    "contact.phone": "Telefón",
    "contact.address": "Adresa",
    "contact.hours": "Pracovné hodiny",
    "contact.emailValue": "podpora@vaii.sk",
    "contact.phoneValue": "+421 900 123 456",
    "contact.addressValue": "Bratislava, Slovensko",
    "contact.hoursValue": "Po-Pia: 9:00 - 17:00",
    "faq.title": "FAQ",
    "faq.q1": "Ako pridám inzerát?",
    "faq.a1":
      "Po prihlásení kliknite na tlačidlo Pridať inzerát a vyplňte všetky povinné polia.",
    "faq.q2": "Ako upravím alebo vymažem inzerát?",
    "faq.a2":
      "Vo svojom účte nájdete zoznam inzerátov. Pri konkrétnom inzeráte zvoľte upraviť alebo odstrániť.",
    "faq.q3": "Ako kontaktujem predajcu?",
    "faq.a3":
      "Na detaile inzerátu kliknite na odoslanie správy. Konverzácie nájdete v sekcii Správy.",
    "faq.q4": "Čo znamená režim predajcu?",
    "faq.a4":
      "Po aktivovaní režimu predajcu budete viditeľní v zozname predajcov.",
    "admin.title": "Admin – správa obsahu",
    "admin.users": "Používatelia",
    "admin.brands": "Značky",
    "admin.models": "Modely",
    "admin.load": "Načítať",
    "admin.close": "Zavrieť",
    "admin.save": "Uložiť",
    "admin.delete": "Odstrániť",
    "admin.role": "Rola",
    "admin.adminAccount": "Admin účet",
    "admin.unknownBrand": "Neznáma značka",
    "admin.filterByBrand": "Filtrovať podľa značky",
    "admin.allBrands": "Všetky značky",
    "admin.noUsers": "Žiadni používatelia.",
    "admin.noBrands": "Žiadne značky.",
    "admin.noModels": "Žiadne modely.",
    "admin.confirmDeleteUser": "Naozaj chcete odstrániť používateľa?",
    "admin.confirmDeleteBrand":
      "Naozaj chcete odstrániť značku? Zmažú sa aj jej modely a inzeráty.",
    "admin.confirmDeleteModel":
      "Naozaj chcete odstrániť model? Zmažú sa aj súvisiace inzeráty.",
    "admin.errorLoad": "Nepodarilo sa načítať admin dáta.",
    "admin.errorUsersLoad": "Používateľov sa nepodarilo načítať.",
    "admin.errorBrandsLoad": "Značky sa nepodarilo načítať.",
    "admin.errorModelsLoad": "Modely sa nepodarilo načítať.",
    "admin.errorDeleteUser": "Používateľa sa nepodarilo odstrániť.",
    "admin.errorDeleteBrand": "Značku sa nepodarilo odstrániť.",
    "admin.errorDeleteModel": "Model sa nepodarilo odstrániť.",
    "admin.errorUpdateBrand": "Značku sa nepodarilo upraviť.",
    "admin.errorUpdateModel": "Model sa nepodarilo upraviť.",
    "admin.errorEmptyBrand": "Názov značky nemôže byť prázdny.",
    "admin.errorEmptyModel": "Názov modelu nemôže byť prázdny.",
    "admin.loading": "Načítavam...",
  },
  en: {
    "common.backHome": "Back to homepage",
    "common.loading": "Loading...",
    "header.addListing": "Add listing",
    "header.sellers": "Sellers",
    "header.favorites": "Favorites",
    "header.messages": "Messages",
    "header.myAccount": "My account",
    "header.admin": "Admin",
    "header.register": "Register",
    "header.login": "Log in",
    "header.logout": "Log out",
    "home.loading": "Loading listings...",
    "home.empty": "No listings found",
    "favorites.title": "Favorites",
    "favorites.loading": "Loading favorites...",
    "favorites.empty": "No favorite listings.",
    "favorites.error": "Failed to load favorites.",
    "messages.title": "Messages",
    "messages.subtitle": "Direct chat between users.",
    "messages.conversations": "Conversations",
    "messages.loadingThreads": "Loading...",
    "messages.noThreads": "No messages yet.",
    "messages.selectConversation": "Select a conversation",
    "messages.loadingMessages": "Loading messages...",
    "messages.noMessages":
      "No messages yet. Contact the user via the listing.",
    "messages.messagePlaceholder": "Write a message...",
    "messages.messagePlaceholderEmpty": "Select a conversation",
    "messages.send": "Send",
    "messages.sending": "Sending...",
    "messages.errorUser": "Failed to load user.",
    "messages.errorThreads": "Failed to load messages.",
    "messages.errorConversation": "Failed to load conversation.",
    "messages.errorSend": "Failed to send message.",
    "messages.errorSelect": "Select a conversation.",
    "messages.userFallback": "User",
    "messages.listingLabel": "Listing:",
    "addListing.titleAdd": "Add listing",
    "addListing.titleEdit": "Edit listing",
    "addListing.loginTitle": "Add listing",
    "addListing.loginText": "Please log in to add a listing.",
    "addListing.loginButton": "Log in",
    "addListing.loading": "Loading...",
    "addListing.submitCreate": "Create listing",
    "addListing.submitEdit": "Save listing",
    "addListing.submitting": "Saving...",
    "addListing.labelTitle": "Title",
    "addListing.labelLocation": "Location",
    "addListing.labelBrand": "Brand",
    "addListing.labelBrandOther": "Brand name",
    "addListing.labelModel": "Model",
    "addListing.labelModelOther": "Model name",
    "addListing.brandPlaceholder": "Select brand",
    "addListing.brandLoading": "Loading brands...",
    "addListing.modelPlaceholder": "Select model",
    "addListing.modelLoading": "Loading models...",
    "addListing.modelPlaceholderSelectBrand": "Select brand first",
    "addListing.modelPlaceholderFillBrand": "Enter model name",
    "addListing.otherBrand": "Other brand",
    "addListing.otherModel": "Other model",
    "addListing.labelYear": "Year",
    "addListing.labelMileage": "Mileage",
    "addListing.labelEngine": "Engine capacity (cc)",
    "addListing.labelPower": "Power (kW)",
    "addListing.labelFuel": "Fuel",
    "addListing.labelTransmission": "Transmission",
    "addListing.labelDrive": "Drive",
    "addListing.labelPrice": "Price",
    "addListing.labelCurrency": "Currency",
    "addListing.labelDescription": "Description",
    "addListing.labelPhotos": "Photos (order 1-10)",
    "addListing.photoChoose": "Choose photo",
    "addListing.photoReplace": "Replace",
    "addListing.fuelPetrol": "Petrol",
    "addListing.fuelDiesel": "Diesel",
    "addListing.fuelElectric": "Electric",
    "addListing.fuelHybrid": "Hybrid",
    "addListing.fuelLpg": "LPG",
    "addListing.transmissionManual": "Manual",
    "addListing.transmissionAutomatic": "Automatic",
    "addListing.driveEmpty": "Not set",
    "addListing.successCreate": "Listing created.",
    "addListing.successEdit": "Listing updated.",
    "addListing.errorLoad": "Failed to load listing.",
    "addListing.errorCreate": "Failed to create listing.",
    "addListing.errorBrands": "Failed to load brands.",
    "footer.about": "About us",
    "footer.contact": "Contact",
    "footer.support": "Support",
    "footer.reportListing": "Report listing",
    "footer.faq": "FAQ",
    "footer.register": "Register",
    "footer.login": "Log in",
    "myAccount.title": "My account",
    "myAccount.nameLabel": "Name:",
    "myAccount.emailLabel": "Email:",
    "myAccount.phoneLabel": "Phone:",
    "myAccount.createdAtLabel": "Account created:",
    "myAccount.accountTypeLabel": "Account type:",
    "myAccount.accountTypeSeller": "Registered seller",
    "myAccount.accountTypeUser": "Regular user",
    "myAccount.sectionEditTitle": "Edit details",
    "myAccount.formPhoneLabel": "Phone",
    "myAccount.formNameLabel": "Name",
    "myAccount.save": "Save",
    "myAccount.saving": "Saving...",
    "myAccount.sellerModeTitle": "Seller mode",
    "myAccount.sellerModeDescription":
      "When enabled, you will appear in the sellers list.",
    "myAccount.sellerModeSaving": "Saving...",
    "myAccount.sellerModeDisable": "Disable seller mode",
    "myAccount.sellerModeEnable": "Become a registered seller",
    "myAccount.deleteTitle": "Delete account",
    "myAccount.deleteDescription":
      "After deletion, all data will be permanently removed.",
    "myAccount.deleteButton": "Delete my account",
    "myAccount.deleteButtonLoading": "Deleting account...",
    "myAccount.errorLoad": "Failed to load user data.",
    "myAccount.errorEmptyName": "Name cannot be empty.",
    "myAccount.successName": "Name updated successfully.",
    "myAccount.errorUpdate": "Failed to update name.",
    "myAccount.successSeller": "Seller setting updated.",
    "myAccount.errorSeller": "Failed to update seller mode.",
    "myAccount.confirmDelete":
      "Are you sure you want to delete your account? This action cannot be undone.",
    "myAccount.alertDeleted": "Your account has been deleted.",
    "myAccount.alertDeleteError": "An error occurred while deleting the account.",
    "myAccount.loading": "Loading user data...",
    "myAccount.userMissing": "User data is not available.",
    "filterBar.brand": "Brand",
    "filterBar.model": "Model",
    "filterBar.all": "All",
    "filterBar.priceFrom": "Price from",
    "filterBar.priceTo": "Price to",
    "filterBar.mileageFrom": "Mileage from",
    "filterBar.mileageTo": "Mileage to",
    "filterBar.yearFrom": "Year from",
    "filterBar.yearTo": "Year to",
    "filterBar.fuel": "Fuel",
    "filterBar.fuelPetrol": "Petrol",
    "filterBar.fuelDiesel": "Diesel",
    "filterBar.fuelElectric": "Electric",
    "filterBar.fuelHybrid": "Hybrid",
    "filterBar.reset": "Reset filters",
    "filterBar.sort": "Sort",
    "filterBar.sortPriceAsc": "Cheapest",
    "filterBar.sortPriceDesc": "Most expensive",
    "filterBar.sortNewest": "Newest",
    "filterBar.sortOldest": "Oldest",
    "filterBar.pageSize": "Listings per page",
    "listingCard.km": "km",
    "listingCard.currency": "EUR",
    "pagination.previous": "Previous",
    "pagination.next": "Next",
    "login.title": "Log in",
    "login.errorInvalid": "Invalid email or password.",
    "login.errorGeneric": "Login failed.",
    "login.placeholderEmail": "Email",
    "login.placeholderPassword": "Password",
    "login.buttonLoading": "Logging in...",
    "login.button": "Log in",
    "register.title": "Register",
    "register.errorPasswordMatch": "Passwords do not match.",
    "register.errorGeneric": "Registration failed.",
    "register.placeholderName": "Name",
    "register.placeholderEmail": "Email",
    "register.placeholderPassword": "Password",
    "register.placeholderPasswordConfirm": "Confirm password",
    "register.buttonLoading": "Registering...",
    "register.button": "Register",
    "sellers.title": "Sellers",
    "sellers.loading": "Loading sellers...",
    "sellers.errorLoad": "Failed to load sellers.",
    "sellers.empty": "There are no registered sellers yet.",
    "sellers.listingsLink": "Seller listings",
    "sellers.registeredLabel": "Registered:",
    "sellerListings.loading": "Loading listings...",
    "sellerListings.errorLoad": "Failed to load seller listings.",
    "sellerListings.backToSellers": "Back to sellers list",
    "sellerListings.title": "Seller listings",
    "sellerListings.unknownSeller": "seller",
    "sellerListings.empty": "No listings found for this seller.",
    "vehicleDetail.notFound": "Listing not found",
    "vehicleDetail.confirmDelete": "Are you sure you want to delete the listing?",
    "vehicleDetail.favoriteRemoveAlt": "Remove favorite",
    "vehicleDetail.favoriteAddAlt": "Add favorite",
    "vehicleDetail.previous": "Previous",
    "vehicleDetail.next": "Next",
    "vehicleDetail.brandLabel": "Brand:",
    "vehicleDetail.modelLabel": "Model:",
    "vehicleDetail.yearLabel": "Year:",
    "vehicleDetail.mileageLabel": "Mileage:",
    "vehicleDetail.fuelLabel": "Fuel:",
    "vehicleDetail.transmissionLabel": "Transmission:",
    "vehicleDetail.driveLabel": "Drive:",
    "vehicleDetail.locationLabel": "Location:",
    "vehicleDetail.contactTitle": "Contact",
    "vehicleDetail.contactButton": "Contact seller",
    "vehicleDetail.contactUnavailable": "Seller contact is not available.",
    "vehicleDetail.reportTitle": "Report listing",
    "vehicleDetail.reportMessage": "Reporting listing:",
    "vehicleDetail.reportSuccess": "Report sent to admins.",
    "vehicleDetail.reportError": "Failed to send the report.",
    "vehicleDetail.reportModalTitle": "Report listing",
    "vehicleDetail.reportPlaceholder": "Short description of the issue...",
    "vehicleDetail.reportSend": "Send",
    "vehicleDetail.reportSending": "Sending...",
    "vehicleDetail.reportCancel": "Cancel",
    "vehicleDetail.descriptionTitle": "Description",
    "vehicleDetail.adminBadge": "Admin mode",
    "vehicleDetail.editButton": "Edit listing",
    "vehicleDetail.deleteButton": "Delete listing",
    "vehicleDetail.contactModalTitle": "Seller contact",
    "vehicleDetail.emailLabel": "Email:",
    "vehicleDetail.phoneLabel": "Phone:",
    "vehicleDetail.sendMessage": "Send message",
    "about.title": "About us",
    "about.p1":
      "VAII Inzercia is where buyers and sellers of vehicles meet. Our goal is simple, fast, and secure listing.",
    "about.p2":
      "We are building a trusted community with clear search tools. Filters, messages, and favorites keep everything in one place.",
    "about.p3":
      "If you have questions or suggestions, reach out. Your feedback matters to us.",
    "contact.title": "Contact",
    "contact.p1": "Have a question or need help? Get in touch with us.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.hours": "Business hours",
    "contact.emailValue": "podpora@vaii.sk",
    "contact.phoneValue": "+421 900 123 456",
    "contact.addressValue": "Bratislava, Slovakia",
    "contact.hoursValue": "Mon-Fri: 9:00 - 17:00",
    "faq.title": "FAQ",
    "faq.q1": "How do I add a listing?",
    "faq.a1":
      "After logging in, click Add listing and fill in all required fields.",
    "faq.q2": "How do I edit or delete a listing?",
    "faq.a2":
      "In your account, open your listings and choose edit or delete on the item.",
    "faq.q3": "How do I contact a seller?",
    "faq.a3":
      "Open the listing detail and send a message. Conversations are in Messages.",
    "faq.q4": "What is seller mode?",
    "faq.a4": "When enabled, you will appear in the sellers list.",
    "admin.title": "Admin - content management",
    "admin.users": "Users",
    "admin.brands": "Brands",
    "admin.models": "Models",
    "admin.load": "Load",
    "admin.close": "Close",
    "admin.save": "Save",
    "admin.delete": "Delete",
    "admin.role": "Role",
    "admin.adminAccount": "Admin account",
    "admin.unknownBrand": "Unknown brand",
    "admin.filterByBrand": "Filter by brand",
    "admin.allBrands": "All brands",
    "admin.noUsers": "No users.",
    "admin.noBrands": "No brands.",
    "admin.noModels": "No models.",
    "admin.confirmDeleteUser": "Are you sure you want to delete this user?",
    "admin.confirmDeleteBrand":
      "Are you sure you want to delete this brand? Its models and listings will be removed.",
    "admin.confirmDeleteModel":
      "Are you sure you want to delete this model? Related listings will be removed.",
    "admin.errorLoad": "Failed to load admin data.",
    "admin.errorUsersLoad": "Failed to load users.",
    "admin.errorBrandsLoad": "Failed to load brands.",
    "admin.errorModelsLoad": "Failed to load models.",
    "admin.errorDeleteUser": "Failed to delete the user.",
    "admin.errorDeleteBrand": "Failed to delete the brand.",
    "admin.errorDeleteModel": "Failed to delete the model.",
    "admin.errorUpdateBrand": "Failed to update the brand.",
    "admin.errorUpdateModel": "Failed to update the model.",
    "admin.errorEmptyBrand": "Brand name cannot be empty.",
    "admin.errorEmptyModel": "Model name cannot be empty.",
    "admin.loading": "Loading...",
  },
};

const LanguageContext = createContext({
  language: "sk",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem("lang") || "sk";
  });

  useEffect(() => {
    localStorage.setItem("lang", language);
  }, [language]);

  const setLanguage = (nextLang) => {
    setLanguageState(nextLang);
  };

  const t = useMemo(() => {
    return (key) =>
      translations[language]?.[key] || translations.sk[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
